--- #YAML:1.0
name:               Catalyst-Authentication-Store-LDAP-AD-Class
version:            0.01
abstract:           The great new Catalyst::Authentication::Store::LDAP::AD::Class!
author:
    - Andrey Chergik <andrey@chergik.ru>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Plugin::Authentication:  0.10003
    Class::Accessor::Fast:  0
    Moose:                0
    Net::LDAP:            0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
